version: '3.7'

services:
  snackhub-mysql-db-customer:
    container_name: snackhub-mysql-db-customer
    restart: always
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=customer
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
  customer:
    build: .
    environment:
      - MYSQL_USER=root
      - MYSQL_PW=123456
      - IP_APP=snackhub-mysql-db-kitchen
      - PORT=3306
    ports:
      - 8090:8090
    depends_on:
      - snackhub-mysql-db-customer
volumes:
  db_data: